import type { SupportedLanguage } from "@prossimo-app/localization/server";

export interface PrivacyPolicySection {
  after?: readonly string[];
  bullets?: readonly string[];
  groups?: readonly {
    after?: readonly string[];
    bullets?: readonly string[];
    paragraphs: readonly string[];
    title: string;
  }[];
  id: string;
  paragraphs?: readonly string[];
  title: string;
}

interface PrivacyPolicyContent {
  contentsLabel: string;
  effectiveDate: string;
  effectiveDateLabel: string;
  intro: {
    appName: string;
    beforeAppName: string;
    beforeWebsite: string;
    websiteUrl: string;
  };
  operator: {
    compliance: string;
    contactEmailLabel: string;
    heading: string;
  };
  sections: readonly PrivacyPolicySection[];
  title: string;
}

export const privacyPolicyContent = {
  en: {
    title: "Privacy Policy",
    contentsLabel: "Contents",
    effectiveDateLabel: "Effective date",
    effectiveDate: "10 June 2026",
    intro: {
      beforeAppName: "This Privacy Policy explains how",
      appName: "Prossimo",
      beforeWebsite:
        '("the App", "we", "us", or "our") collects, uses, and protects information when you use the Prossimo mobile application and the website available at',
      websiteUrl: "https://prossimo.app",
    },
    operator: {
      heading: "Operator",
      contactEmailLabel: "Contact email:",
      compliance:
        "This Privacy Policy is intended to comply with applicable privacy laws, including the General Data Protection Regulation (GDPR), where applicable.",
    },
    sections: [
      {
        id: "overview",
        title: "1. Overview",
        paragraphs: [
          "Prossimo is a public transport tracking application for Torino. The App provides information about stops, routes, estimated arrivals, vehicle positions, and service updates using official public transport data sources, including GTT/5T/GTFS/GTFS-RT data.",
          "The App is free to use. It does not require users to create an account. We do not sell personal data. We do not use advertising.",
        ],
      },
      {
        id: "information-we-collect",
        title: "2. Information We Collect",
        groups: [
          {
            title: "Location Data",
            paragraphs: [
              "With your permission, Prossimo may access your precise device location.",
              "Location data is used only to provide App features such as:",
            ],
            bullets: [
              "showing nearby stops;",
              "showing nearby public transport options;",
              "improving map-based functionality;",
              "helping you navigate public transport information more easily.",
            ],
            after: [
              "Your precise location is not stored on our servers.",
              "You can disable location access at any time through your device settings.",
            ],
          },
          {
            title: "Device and Usage Data",
            paragraphs: [
              "We may collect limited technical information through Expo Insights, such as device type, operating system, app version, and basic performance information, to monitor the reliability of the App.",
              'In addition, if you enable "Activity tracking" in the App settings, we collect usage analytics through PostHog, an analytics service hosted in the European Union. This includes:',
            ],
            bullets: [
              "an anonymous install identifier: a random identifier generated on your device the first time you launch the App, stored only on your device, and shared with PostHog only in irreversibly hashed (SHA-256) form; it is not derived from your device hardware or any personal information, does not identify you personally, and is deleted and replaced with a new one if you uninstall and reinstall the App;",
              "interactions with App features, such as which screens you view and which stops, lines, and vehicles you select;",
              "changes to App settings, such as theme, language, and notification preferences;",
              "device type, operating system, and app version.",
            ],
            after: [
              "Usage analytics are collected only with your consent and are used solely to understand how the App is used and to improve it. Your precise device location is never sent to our analytics provider.",
              'You can withdraw your consent at any time by turning off "Activity tracking" in the App settings, after which no further analytics data is collected.',
            ],
          },
          {
            title: "Push Notification Data",
            paragraphs: [
              "If you enable push notifications, the App may collect and use a push notification token generated by your device or platform provider.",
              "This token is used only to send notifications related to the App, such as transit updates or service-related messages.",
              "You can disable notifications at any time through your device settings.",
            ],
          },
          {
            title: "Maps and Google Maps on Android",
            paragraphs: [
              "On Android devices, Prossimo may use Google Maps to display map-based features, including your current location, nearby stops, and stop markers.",
              "When you use map features, Google may process certain information according to Google's own terms and privacy policy. This may include technical information about your device, app usage related to map display, and location-related information when location features are enabled.",
              "Prossimo uses your location with Google Maps only to provide map-based public transport features, such as showing your position in relation to nearby stops. Prossimo does not store your precise location on its servers and does not use your location for advertising or marketing.",
              "You can disable location access at any time through your device settings. If you disable location access, map features may still be available, but your current location may not be shown.",
              "Google Maps content, map tiles, logos, and related map data are provided by Google and are subject to Google's own terms and privacy policy.",
            ],
          },
        ],
      },
      {
        id: "information-we-do-not-collect",
        title: "3. Information We Do Not Collect",
        paragraphs: ["Prossimo does not:"],
        bullets: [
          "require user accounts;",
          "collect passwords;",
          "store your precise location history on our servers;",
          "sell personal data;",
          "share personal data for advertising or marketing purposes;",
          "use third-party advertising networks;",
          "collect payment information.",
        ],
      },
      {
        id: "how-we-use-information",
        title: "4. How We Use Information",
        paragraphs: ["We use information only for the following purposes:"],
        bullets: [
          "to provide core App functionality;",
          "to show nearby stops and map-based transport information;",
          "to send push notifications if enabled;",
          "to monitor App performance;",
          "to understand how App features are used, where you have consented to activity tracking;",
          "to improve reliability and user experience;",
          "to protect the App from misuse or technical issues;",
          "to comply with legal obligations, where required.",
        ],
      },
      {
        id: "location-and-map-features",
        title: "5. Location and Map Features",
        paragraphs: [
          "The App may use your device location, with your permission, to show your current position, nearby stops, stop markers, and other map-based public transport information.",
          "On Android devices, Prossimo may use Google Maps to display maps, your current location, and stop markers. Google Maps content is provided by Google and is subject to Google's own terms, policies, and attribution requirements.",
          "On supported Apple devices, Prossimo may use Apple Maps for map-based features.",
          "You are responsible for enabling or disabling location access through your device settings. If location access is disabled, some map-based features may not work as expected.",
          "Map data, transit data, location results, and visual map content may be inaccurate, delayed, incomplete, or unavailable. You should not rely solely on map features or location features for time-critical travel decisions.",
        ],
      },
      {
        id: "legal-basis",
        title: "6. Legal Basis for Processing",
        paragraphs: [
          "Where GDPR applies, we process personal data based on the following legal bases:",
        ],
        bullets: [
          "Consent: for accessing your device location, sending push notifications, and collecting usage analytics about how you use the App.",
          "Legitimate interest: for monitoring App performance, preventing abuse, and maintaining the security and reliability of the App.",
          "Legal obligation: where processing is necessary to comply with applicable law.",
        ],
        after: [
          'You may withdraw consent for location access or notifications at any time through your device settings, and for usage analytics at any time by turning off "Activity tracking" in the App settings.',
        ],
      },
      {
        id: "third-party-services",
        title: "7. Third-Party Services",
        paragraphs: [
          "Prossimo may use third-party services to operate and improve the App, including:",
        ],
        bullets: [
          "Expo Insights for basic app performance and reliability information;",
          "PostHog, a product analytics service hosted in the European Union, used to understand how the App is used — only if you have enabled activity tracking, and only using the hashed anonymous install identifier described above;",
          "Google Maps, used on Android to display maps, user location, and stop markers;",
          "Apple Maps, used on supported Apple devices to display maps and location-based features;",
          "infrastructure and hosting providers necessary to operate the App.",
        ],
        after: [
          "These third parties may process data according to their own privacy policies.",
        ],
      },
      {
        id: "data-sharing",
        title: "8. Data Sharing",
        paragraphs: [
          "We do not sell personal data.",
          "We may share limited information only when necessary with:",
        ],
        bullets: [
          "technical service providers that help us operate the App;",
          "analytics or infrastructure providers;",
          "public authorities, if required by law.",
        ],
        after: [
          "We do not share your personal data for third-party marketing or advertising.",
        ],
      },
      {
        id: "data-retention",
        title: "9. Data Retention",
        paragraphs: [
          "We keep personal data only for as long as necessary for the purposes described in this Privacy Policy.",
          "Precise location data is not stored on our servers.",
          "Push notification tokens may be retained for as long as notifications are enabled or as long as necessary to provide notification functionality.",
          "Technical and usage information may be retained for a limited period to monitor performance, debug issues, and improve the App.",
          "Usage analytics associated with the hashed anonymous install identifier are retained by our analytics provider only for as long as necessary to analyze and improve the App. If you withdraw your consent, no further analytics data is collected.",
        ],
      },
      {
        id: "security",
        title: "10. Security",
        paragraphs: [
          "We use reasonable technical and organizational measures to protect information processed through the App.",
          "However, no method of transmission or storage is completely secure, and we cannot guarantee absolute security.",
        ],
      },
      {
        id: "your-rights",
        title: "11. Your Rights",
        paragraphs: [
          "Where applicable, including under the GDPR, you may have the right to:",
        ],
        bullets: [
          "access your personal data;",
          "request correction of inaccurate data;",
          "request deletion of your data;",
          "object to certain processing;",
          "restrict certain processing;",
          "withdraw consent;",
          "request data portability, where applicable;",
          "lodge a complaint with a data protection authority.",
        ],
        after: [
          "In Italy, you may contact the Garante per la protezione dei dati personali.",
          "To exercise your rights, contact us at:",
        ],
      },
      {
        id: "childrens-privacy",
        title: "12. Children's Privacy",
        paragraphs: [
          "Prossimo is not intended for children under the age required by applicable law to use digital services without parental consent.",
          "We do not knowingly collect personal data from children.",
        ],
      },
      {
        id: "cookies-and-similar-technologies",
        title: "13. Cookies and Similar Technologies",
        paragraphs: [
          "The Prossimo mobile app does not use browser cookies.",
          "The website at https://prossimo.app may use only strictly necessary technical technologies required for the website to function. We do not use advertising cookies or marketing cookies.",
          "If we introduce analytics, embedded third-party content, or other non-essential cookies in the future, we will update this Privacy Policy and, where required, request consent.",
        ],
      },
      {
        id: "international-transfers",
        title: "14. International Transfers",
        paragraphs: [
          "Some service providers used by the App may process data outside your country of residence.",
          "Usage analytics collected through PostHog are processed on servers located in the European Union.",
          "Where required, we rely on appropriate safeguards for international data transfers.",
        ],
      },
      {
        id: "changes",
        title: "15. Changes to This Privacy Policy",
        paragraphs: [
          "We may update this Privacy Policy from time to time.",
          "If we make changes, we will update the effective date above and publish the updated version in the App or on our website.",
        ],
      },
      {
        id: "contact",
        title: "16. Contact",
        paragraphs: [
          "For questions about this Privacy Policy or how your data is handled, contact:",
        ],
      },
    ],
  },
  it: {
    title: "Informativa sulla privacy",
    contentsLabel: "Indice",
    effectiveDateLabel: "Data di entrata in vigore",
    effectiveDate: "10 giugno 2026",
    intro: {
      beforeAppName: "La presente Informativa sulla privacy spiega come",
      appName: "Prossimo",
      beforeWebsite:
        '("l\'App", "noi", "ci" o "nostro") raccoglie, utilizza e protegge le informazioni quando usi l\'applicazione mobile Prossimo e il sito web disponibile all\'indirizzo',
      websiteUrl: "https://prossimo.app",
    },
    operator: {
      heading: "Titolare",
      contactEmailLabel: "Email di contatto:",
      compliance:
        "La presente Informativa sulla privacy è pensata per rispettare le leggi applicabili in materia di privacy, incluso il Regolamento generale sulla protezione dei dati (GDPR), ove applicabile.",
    },
    sections: [
      {
        id: "overview",
        title: "1. Panoramica",
        paragraphs: [
          "Prossimo è un'applicazione per il monitoraggio del trasporto pubblico a Torino. L'App fornisce informazioni su fermate, percorsi, arrivi stimati, posizioni dei veicoli e aggiornamenti sul servizio utilizzando fonti ufficiali di dati sul trasporto pubblico, inclusi dati GTT/5T/GTFS/GTFS-RT.",
          "L'App è gratuita. Non richiede agli utenti di creare un account. Non vendiamo dati personali. Non utilizziamo pubblicità.",
        ],
      },
      {
        id: "information-we-collect",
        title: "2. Informazioni che raccogliamo",
        groups: [
          {
            title: "Dati sulla posizione",
            paragraphs: [
              "Con il tuo consenso, Prossimo può accedere alla posizione precisa del tuo dispositivo.",
              "I dati sulla posizione sono utilizzati solo per fornire funzionalità dell'App come:",
            ],
            bullets: [
              "mostrare le fermate nelle vicinanze;",
              "mostrare le opzioni di trasporto pubblico nelle vicinanze;",
              "migliorare le funzionalità basate sulla mappa;",
              "aiutarti a consultare più facilmente le informazioni sul trasporto pubblico.",
            ],
            after: [
              "La tua posizione precisa non viene memorizzata sui nostri server.",
              "Puoi disattivare l'accesso alla posizione in qualsiasi momento dalle impostazioni del dispositivo.",
            ],
          },
          {
            title: "Dati del dispositivo e di utilizzo",
            paragraphs: [
              "Potremmo raccogliere informazioni tecniche limitate tramite Expo Insights, come tipo di dispositivo, sistema operativo, versione dell'app e informazioni di base sulle prestazioni, per monitorare l'affidabilità dell'App.",
              'Inoltre, se attivi il "Tracciamento dell\'attività" nelle impostazioni dell\'App, raccogliamo dati analitici di utilizzo tramite PostHog, un servizio di analisi ospitato nell\'Unione Europea. Questo include:',
            ],
            bullets: [
              "un identificatore anonimo di installazione: un identificatore casuale generato sul tuo dispositivo al primo avvio dell'App, memorizzato solo sul tuo dispositivo e condiviso con PostHog esclusivamente in forma irreversibilmente cifrata tramite hash (SHA-256); non deriva dall'hardware del tuo dispositivo né da informazioni personali, non ti identifica personalmente e viene eliminato e sostituito con uno nuovo se disinstalli e reinstalli l'App;",
              "interazioni con le funzionalità dell'App, come le schermate che visualizzi e le fermate, le linee e i veicoli che selezioni;",
              "modifiche alle impostazioni dell'App, come tema, lingua e preferenze di notifica;",
              "tipo di dispositivo, sistema operativo e versione dell'app.",
            ],
            after: [
              "I dati analitici di utilizzo sono raccolti solo con il tuo consenso e sono utilizzati esclusivamente per comprendere come viene utilizzata l'App e per migliorarla. La posizione precisa del tuo dispositivo non viene mai inviata al nostro fornitore di analisi.",
              'Puoi revocare il consenso in qualsiasi momento disattivando il "Tracciamento dell\'attività" nelle impostazioni dell\'App; da quel momento non verranno più raccolti dati analitici.',
            ],
          },
          {
            title: "Dati per le notifiche push",
            paragraphs: [
              "Se abiliti le notifiche push, l'App può raccogliere e utilizzare un token di notifica push generato dal tuo dispositivo o dal fornitore della piattaforma.",
              "Questo token è utilizzato solo per inviare notifiche relative all'App, come aggiornamenti sul trasporto pubblico o messaggi relativi al servizio.",
              "Puoi disattivare le notifiche in qualsiasi momento dalle impostazioni del dispositivo.",
            ],
          },
          {
            title: "Mappe e Google Maps su Android",
            paragraphs: [
              "Sui dispositivi Android, Prossimo puo utilizzare Google Maps per mostrare funzionalita basate sulla mappa, inclusa la tua posizione attuale, le fermate vicine e gli indicatori delle fermate.",
              "Quando usi le funzionalita di mappa, Google puo trattare alcune informazioni secondo i propri termini e la propria informativa sulla privacy. Questo puo includere informazioni tecniche sul tuo dispositivo, l'utilizzo dell'app relativo alla visualizzazione della mappa e informazioni relative alla posizione quando le funzionalita di localizzazione sono abilitate.",
              "Prossimo usa la tua posizione con Google Maps solo per fornire funzionalita di trasporto pubblico basate sulla mappa, come mostrare la tua posizione rispetto alle fermate vicine. Prossimo non memorizza la tua posizione precisa sui propri server e non usa la tua posizione per pubblicita o marketing.",
              "Puoi disattivare l'accesso alla posizione in qualsiasi momento dalle impostazioni del dispositivo. Se disattivi l'accesso alla posizione, le funzionalita di mappa possono rimanere disponibili, ma la tua posizione attuale potrebbe non essere mostrata.",
              "I contenuti di Google Maps, i riquadri della mappa, i loghi e i relativi dati cartografici sono forniti da Google e sono soggetti ai termini e all'informativa sulla privacy di Google.",
            ],
          },
        ],
      },
      {
        id: "information-we-do-not-collect",
        title: "3. Informazioni che non raccogliamo",
        paragraphs: ["Prossimo non:"],
        bullets: [
          "richiede account utente;",
          "raccoglie password;",
          "memorizza sui nostri server la cronologia precisa della tua posizione;",
          "vende dati personali;",
          "condivide dati personali per finalità pubblicitarie o di marketing;",
          "utilizza reti pubblicitarie di terze parti;",
          "raccoglie informazioni di pagamento.",
        ],
      },
      {
        id: "how-we-use-information",
        title: "4. Come utilizziamo le informazioni",
        paragraphs: [
          "Utilizziamo le informazioni solo per le seguenti finalità:",
        ],
        bullets: [
          "fornire le funzionalità principali dell'App;",
          "mostrare fermate nelle vicinanze e informazioni sul trasporto basate sulla mappa;",
          "inviare notifiche push, se abilitate;",
          "monitorare le prestazioni dell'App;",
          "comprendere come vengono utilizzate le funzionalità dell'App, ove tu abbia acconsentito al tracciamento dell'attività;",
          "migliorare affidabilità ed esperienza utente;",
          "proteggere l'App da usi impropri o problemi tecnici;",
          "rispettare obblighi di legge, ove richiesto.",
        ],
      },
      {
        id: "location-and-map-features",
        title: "5. Posizione e funzionalita di mappa",
        paragraphs: [
          "L'App puo utilizzare la posizione del tuo dispositivo, con il tuo permesso, per mostrare la tua posizione attuale, le fermate vicine, gli indicatori delle fermate e altre informazioni sul trasporto pubblico basate sulla mappa.",
          "Sui dispositivi Android, Prossimo puo utilizzare Google Maps per mostrare mappe, la tua posizione attuale e gli indicatori delle fermate. I contenuti di Google Maps sono forniti da Google e sono soggetti ai termini, alle policy e ai requisiti di attribuzione di Google.",
          "Sui dispositivi Apple supportati, Prossimo puo utilizzare Apple Maps per le funzionalita basate sulla mappa.",
          "Sei responsabile dell'attivazione o disattivazione dell'accesso alla posizione dalle impostazioni del dispositivo. Se l'accesso alla posizione e disabilitato, alcune funzionalita basate sulla mappa potrebbero non funzionare come previsto.",
          "Dati cartografici, dati del trasporto, risultati di localizzazione e contenuti visivi della mappa possono essere inesatti, in ritardo, incompleti o non disponibili. Non dovresti affidarti esclusivamente alle funzionalita di mappa o di localizzazione per decisioni di viaggio urgenti.",
        ],
      },
      {
        id: "legal-basis",
        title: "6. Base giuridica del trattamento",
        paragraphs: [
          "Ove si applichi il GDPR, trattiamo i dati personali sulla base delle seguenti basi giuridiche:",
        ],
        bullets: [
          "Consenso: per accedere alla posizione del dispositivo, inviare notifiche push e raccogliere dati analitici su come utilizzi l'App.",
          "Legittimo interesse: per monitorare le prestazioni dell'App, prevenire abusi e mantenere sicurezza e affidabilità dell'App.",
          "Obbligo legale: quando il trattamento è necessario per rispettare la legge applicabile.",
        ],
        after: [
          'Puoi revocare il consenso per l\'accesso alla posizione o per le notifiche in qualsiasi momento dalle impostazioni del dispositivo, e per i dati analitici di utilizzo in qualsiasi momento disattivando il "Tracciamento dell\'attività" nelle impostazioni dell\'App.',
        ],
      },
      {
        id: "third-party-services",
        title: "7. Servizi di terze parti",
        paragraphs: [
          "Prossimo può utilizzare servizi di terze parti per gestire e migliorare l'App, inclusi:",
        ],
        bullets: [
          "Expo Insights per informazioni di base su prestazioni e affidabilità dell'app;",
          "PostHog, un servizio di analisi di prodotto ospitato nell'Unione Europea, usato per comprendere come viene utilizzata l'App — solo se hai attivato il tracciamento dell'attività e solo tramite l'identificatore anonimo di installazione cifrato tramite hash descritto sopra;",
          "Google Maps, usato su Android per mostrare mappe, posizione dell'utente e indicatori delle fermate;",
          "Apple Maps, usato sui dispositivi Apple supportati per mostrare mappe e funzionalita basate sulla posizione;",
          "fornitori di infrastruttura e hosting necessari per il funzionamento dell'App.",
        ],
        after: [
          "Queste terze parti possono trattare dati secondo le rispettive informative sulla privacy.",
        ],
      },
      {
        id: "data-sharing",
        title: "8. Condivisione dei dati",
        paragraphs: [
          "Non vendiamo dati personali.",
          "Possiamo condividere informazioni limitate solo quando necessario con:",
        ],
        bullets: [
          "fornitori tecnici che ci aiutano a gestire l'App;",
          "fornitori di analisi o infrastruttura;",
          "autorità pubbliche, se richiesto dalla legge.",
        ],
        after: [
          "Non condividiamo i tuoi dati personali per marketing o pubblicità di terze parti.",
        ],
      },
      {
        id: "data-retention",
        title: "9. Conservazione dei dati",
        paragraphs: [
          "Conserviamo i dati personali solo per il tempo necessario alle finalità descritte nella presente Informativa sulla privacy.",
          "I dati sulla posizione precisa non vengono memorizzati sui nostri server.",
          "I token per le notifiche push possono essere conservati finché le notifiche sono abilitate o per il tempo necessario a fornire la funzionalità di notifica.",
          "Le informazioni tecniche e di utilizzo possono essere conservate per un periodo limitato per monitorare le prestazioni, risolvere problemi e migliorare l'App.",
          "I dati analitici di utilizzo associati all'identificatore anonimo di installazione cifrato tramite hash sono conservati dal nostro fornitore di analisi solo per il tempo necessario ad analizzare e migliorare l'App. Se revochi il consenso, non verranno più raccolti dati analitici.",
        ],
      },
      {
        id: "security",
        title: "10. Sicurezza",
        paragraphs: [
          "Utilizziamo misure tecniche e organizzative ragionevoli per proteggere le informazioni trattate tramite l'App.",
          "Tuttavia, nessun metodo di trasmissione o archiviazione è completamente sicuro e non possiamo garantire una sicurezza assoluta.",
        ],
      },
      {
        id: "your-rights",
        title: "11. I tuoi diritti",
        paragraphs: [
          "Ove applicabile, anche ai sensi del GDPR, potresti avere il diritto di:",
        ],
        bullets: [
          "accedere ai tuoi dati personali;",
          "richiedere la rettifica di dati inesatti;",
          "richiedere la cancellazione dei tuoi dati;",
          "opporti a determinati trattamenti;",
          "limitare determinati trattamenti;",
          "revocare il consenso;",
          "richiedere la portabilità dei dati, ove applicabile;",
          "presentare un reclamo a un'autorità per la protezione dei dati.",
        ],
        after: [
          "In Italia puoi contattare il Garante per la protezione dei dati personali.",
          "Per esercitare i tuoi diritti, contattaci all'indirizzo:",
        ],
      },
      {
        id: "childrens-privacy",
        title: "12. Privacy dei minori",
        paragraphs: [
          "Prossimo non è destinata a minori che non abbiano l'età richiesta dalla legge applicabile per utilizzare servizi digitali senza il consenso dei genitori.",
          "Non raccogliamo consapevolmente dati personali da minori.",
        ],
      },
      {
        id: "cookies-and-similar-technologies",
        title: "13. Cookie e tecnologie simili",
        paragraphs: [
          "L'app mobile Prossimo non usa cookie del browser.",
          "Il sito web https://prossimo.app puo usare solo tecnologie tecniche strettamente necessarie al funzionamento del sito. Non usiamo cookie pubblicitari o cookie di marketing.",
          "Se in futuro introdurremo analytics, contenuti incorporati di terze parti o altri cookie non essenziali, aggiorneremo la presente Informativa sulla privacy e, ove richiesto, chiederemo il consenso.",
        ],
      },
      {
        id: "international-transfers",
        title: "14. Trasferimenti internazionali",
        paragraphs: [
          "Alcuni fornitori di servizi utilizzati dall'App possono trattare dati al di fuori del tuo paese di residenza.",
          "I dati analitici di utilizzo raccolti tramite PostHog sono trattati su server situati nell'Unione Europea.",
          "Ove richiesto, ci basiamo su garanzie adeguate per i trasferimenti internazionali di dati.",
        ],
      },
      {
        id: "changes",
        title: "15. Modifiche alla presente Informativa sulla privacy",
        paragraphs: [
          "Possiamo aggiornare la presente Informativa sulla privacy di tanto in tanto.",
          "In caso di modifiche, aggiorneremo la data di entrata in vigore sopra indicata e pubblicheremo la versione aggiornata nell'App o sul nostro sito web.",
        ],
      },
      {
        id: "contact",
        title: "16. Contatti",
        paragraphs: [
          "Per domande sulla presente Informativa sulla privacy o su come vengono gestiti i tuoi dati, contatta:",
        ],
      },
    ],
  },
} satisfies Record<SupportedLanguage, PrivacyPolicyContent>;
