import type { SupportedLanguage } from "@prossimo-app/localization/server";

export type PrivacyPolicySection = {
  after?: readonly string[];
  bullets?: readonly string[];
  groups?: readonly {
    after?: readonly string[];
    bullets?: readonly string[];
    paragraphs: readonly string[];
    title: string;
  }[];
  id: string;
  paragraphs?: readonly string[];
  title: string;
};

type PrivacyPolicyContent = {
  contentsLabel: string;
  effectiveDate: string;
  effectiveDateLabel: string;
  intro: {
    appName: string;
    beforeAppName: string;
    beforeWebsite: string;
    websiteUrl: string;
  };
  operator: {
    compliance: string;
    contactEmailLabel: string;
    heading: string;
  };
  sections: readonly PrivacyPolicySection[];
  title: string;
};

export const privacyPolicyContent = {
  en: {
    title: "Privacy Policy",
    contentsLabel: "Contents",
    effectiveDateLabel: "Effective date",
    effectiveDate: "5 June 2026",
    intro: {
      beforeAppName: "This Privacy Policy explains how",
      appName: "Prossimo",
      beforeWebsite:
        '("the App", "we", "us", or "our") collects, uses, and protects information when you use the Prossimo mobile application and the website available at',
      websiteUrl: "https://prossimo.app",
    },
    operator: {
      heading: "Operator",
      contactEmailLabel: "Contact email:",
      compliance:
        "This Privacy Policy is intended to comply with applicable privacy laws, including the General Data Protection Regulation (GDPR), where applicable.",
    },
    sections: [
      {
        id: "overview",
        title: "1. Overview",
        paragraphs: [
          "Prossimo is a public transport tracking application for Torino. The App provides information about stops, routes, estimated arrivals, vehicle positions, and service updates using official public transport data sources, including GTT/5T/GTFS/GTFS-RT data.",
          "The App is free to use. It does not require users to create an account. We do not sell personal data. We do not use advertising.",
        ],
      },
      {
        id: "information-we-collect",
        title: "2. Information We Collect",
        groups: [
          {
            title: "Location Data",
            paragraphs: [
              "With your permission, Prossimo may access your precise device location.",
              "Location data is used only to provide App features such as:",
            ],
            bullets: [
              "showing nearby stops;",
              "showing nearby public transport options;",
              "improving map-based functionality;",
              "helping you navigate public transport information more easily.",
            ],
            after: [
              "Your precise location is not stored on our servers.",
              "You can disable location access at any time through your device settings.",
            ],
          },
          {
            title: "Device and Usage Data",
            paragraphs: [
              "We may collect limited technical and usage information through Expo Insights, such as:",
            ],
            bullets: [
              "device type;",
              "operating system;",
              "app version;",
              "basic usage and performance information;",
              "aggregated information about how the App is used.",
            ],
            after: [
              "This information helps us understand app performance and improve the reliability and usability of Prossimo.",
            ],
          },
          {
            title: "Push Notification Data",
            paragraphs: [
              "If you enable push notifications, the App may collect and use a push notification token generated by your device or platform provider.",
              "This token is used only to send notifications related to the App, such as transit updates or service-related messages.",
              "You can disable notifications at any time through your device settings.",
            ],
          },
          {
            title: "Maps and Third-Party Map Services",
            paragraphs: [
              "Prossimo may use Apple Maps and Google Maps to display map-related features.",
              "When you use map features, Apple or Google may process certain information according to their own privacy policies and terms. We do not control how these third-party map providers process information.",
            ],
          },
        ],
      },
      {
        id: "information-we-do-not-collect",
        title: "3. Information We Do Not Collect",
        paragraphs: ["Prossimo does not:"],
        bullets: [
          "require user accounts;",
          "collect passwords;",
          "store your precise location history on our servers;",
          "sell personal data;",
          "share personal data for advertising or marketing purposes;",
          "use third-party advertising networks;",
          "collect payment information.",
        ],
      },
      {
        id: "how-we-use-information",
        title: "4. How We Use Information",
        paragraphs: ["We use information only for the following purposes:"],
        bullets: [
          "to provide core App functionality;",
          "to show nearby stops and map-based transport information;",
          "to send push notifications if enabled;",
          "to monitor App performance;",
          "to improve reliability and user experience;",
          "to protect the App from misuse or technical issues;",
          "to comply with legal obligations, where required.",
        ],
      },
      {
        id: "legal-basis",
        title: "5. Legal Basis for Processing",
        paragraphs: [
          "Where GDPR applies, we process personal data based on the following legal bases:",
        ],
        bullets: [
          "Consent: for accessing your device location and sending push notifications.",
          "Legitimate interest: for improving App performance, understanding general usage, preventing abuse, and maintaining the security and reliability of the App.",
          "Legal obligation: where processing is necessary to comply with applicable law.",
        ],
        after: [
          "You may withdraw consent for location access or notifications at any time through your device settings.",
        ],
      },
      {
        id: "third-party-services",
        title: "6. Third-Party Services",
        paragraphs: [
          "Prossimo may use third-party services to operate and improve the App, including:",
        ],
        bullets: [
          "Expo Insights for basic app usage and performance information;",
          "Apple Maps for map functionality on supported devices;",
          "Google Maps for map functionality on supported devices;",
          "infrastructure and hosting providers necessary to operate the App.",
        ],
        after: [
          "These third parties may process data according to their own privacy policies.",
        ],
      },
      {
        id: "data-sharing",
        title: "7. Data Sharing",
        paragraphs: [
          "We do not sell personal data.",
          "We may share limited information only when necessary with:",
        ],
        bullets: [
          "technical service providers that help us operate the App;",
          "analytics or infrastructure providers;",
          "public authorities, if required by law.",
        ],
        after: [
          "We do not share your personal data for third-party marketing or advertising.",
        ],
      },
      {
        id: "data-retention",
        title: "8. Data Retention",
        paragraphs: [
          "We keep personal data only for as long as necessary for the purposes described in this Privacy Policy.",
          "Precise location data is not stored on our servers.",
          "Push notification tokens may be retained for as long as notifications are enabled or as long as necessary to provide notification functionality.",
          "Technical and usage information may be retained for a limited period to monitor performance, debug issues, and improve the App.",
        ],
      },
      {
        id: "security",
        title: "9. Security",
        paragraphs: [
          "We use reasonable technical and organizational measures to protect information processed through the App.",
          "However, no method of transmission or storage is completely secure, and we cannot guarantee absolute security.",
        ],
      },
      {
        id: "your-rights",
        title: "10. Your Rights",
        paragraphs: [
          "Where applicable, including under the GDPR, you may have the right to:",
        ],
        bullets: [
          "access your personal data;",
          "request correction of inaccurate data;",
          "request deletion of your data;",
          "object to certain processing;",
          "restrict certain processing;",
          "withdraw consent;",
          "request data portability, where applicable;",
          "lodge a complaint with a data protection authority.",
        ],
        after: [
          "In Italy, you may contact the Garante per la protezione dei dati personali.",
          "To exercise your rights, contact us at:",
        ],
      },
      {
        id: "childrens-privacy",
        title: "11. Children's Privacy",
        paragraphs: [
          "Prossimo is not intended for children under the age required by applicable law to use digital services without parental consent.",
          "We do not knowingly collect personal data from children.",
        ],
      },
      {
        id: "international-transfers",
        title: "12. International Transfers",
        paragraphs: [
          "Some service providers used by the App may process data outside your country of residence.",
          "Where required, we rely on appropriate safeguards for international data transfers.",
        ],
      },
      {
        id: "changes",
        title: "13. Changes to This Privacy Policy",
        paragraphs: [
          "We may update this Privacy Policy from time to time.",
          "If we make changes, we will update the effective date above and publish the updated version in the App or on our website.",
        ],
      },
      {
        id: "contact",
        title: "14. Contact",
        paragraphs: [
          "For questions about this Privacy Policy or how your data is handled, contact:",
        ],
      },
    ],
  },
  it: {
    title: "Informativa sulla privacy",
    contentsLabel: "Indice",
    effectiveDateLabel: "Data di entrata in vigore",
    effectiveDate: "5 giugno 2026",
    intro: {
      beforeAppName: "La presente Informativa sulla privacy spiega come",
      appName: "Prossimo",
      beforeWebsite:
        '("l\'App", "noi", "ci" o "nostro") raccoglie, utilizza e protegge le informazioni quando usi l\'applicazione mobile Prossimo e il sito web disponibile all\'indirizzo',
      websiteUrl: "https://prossimo.app",
    },
    operator: {
      heading: "Titolare",
      contactEmailLabel: "Email di contatto:",
      compliance:
        "La presente Informativa sulla privacy è pensata per rispettare le leggi applicabili in materia di privacy, incluso il Regolamento generale sulla protezione dei dati (GDPR), ove applicabile.",
    },
    sections: [
      {
        id: "overview",
        title: "1. Panoramica",
        paragraphs: [
          "Prossimo è un'applicazione per il monitoraggio del trasporto pubblico a Torino. L'App fornisce informazioni su fermate, percorsi, arrivi stimati, posizioni dei veicoli e aggiornamenti sul servizio utilizzando fonti ufficiali di dati sul trasporto pubblico, inclusi dati GTT/5T/GTFS/GTFS-RT.",
          "L'App è gratuita. Non richiede agli utenti di creare un account. Non vendiamo dati personali. Non utilizziamo pubblicità.",
        ],
      },
      {
        id: "information-we-collect",
        title: "2. Informazioni che raccogliamo",
        groups: [
          {
            title: "Dati sulla posizione",
            paragraphs: [
              "Con il tuo consenso, Prossimo può accedere alla posizione precisa del tuo dispositivo.",
              "I dati sulla posizione sono utilizzati solo per fornire funzionalità dell'App come:",
            ],
            bullets: [
              "mostrare le fermate nelle vicinanze;",
              "mostrare le opzioni di trasporto pubblico nelle vicinanze;",
              "migliorare le funzionalità basate sulla mappa;",
              "aiutarti a consultare più facilmente le informazioni sul trasporto pubblico.",
            ],
            after: [
              "La tua posizione precisa non viene memorizzata sui nostri server.",
              "Puoi disattivare l'accesso alla posizione in qualsiasi momento dalle impostazioni del dispositivo.",
            ],
          },
          {
            title: "Dati del dispositivo e di utilizzo",
            paragraphs: [
              "Potremmo raccogliere informazioni tecniche e di utilizzo limitate tramite Expo Insights, come:",
            ],
            bullets: [
              "tipo di dispositivo;",
              "sistema operativo;",
              "versione dell'app;",
              "informazioni di base su utilizzo e prestazioni;",
              "informazioni aggregate su come viene utilizzata l'App.",
            ],
            after: [
              "Queste informazioni ci aiutano a comprendere le prestazioni dell'app e a migliorare l'affidabilità e l'usabilità di Prossimo.",
            ],
          },
          {
            title: "Dati per le notifiche push",
            paragraphs: [
              "Se abiliti le notifiche push, l'App può raccogliere e utilizzare un token di notifica push generato dal tuo dispositivo o dal fornitore della piattaforma.",
              "Questo token è utilizzato solo per inviare notifiche relative all'App, come aggiornamenti sul trasporto pubblico o messaggi relativi al servizio.",
              "Puoi disattivare le notifiche in qualsiasi momento dalle impostazioni del dispositivo.",
            ],
          },
          {
            title: "Mappe e servizi di mappe di terze parti",
            paragraphs: [
              "Prossimo può utilizzare Apple Maps e Google Maps per mostrare funzionalità relative alle mappe.",
              "Quando usi le funzionalità di mappa, Apple o Google possono trattare alcune informazioni secondo le rispettive informative sulla privacy e condizioni. Non controlliamo il modo in cui questi fornitori terzi di mappe trattano le informazioni.",
            ],
          },
        ],
      },
      {
        id: "information-we-do-not-collect",
        title: "3. Informazioni che non raccogliamo",
        paragraphs: ["Prossimo non:"],
        bullets: [
          "richiede account utente;",
          "raccoglie password;",
          "memorizza sui nostri server la cronologia precisa della tua posizione;",
          "vende dati personali;",
          "condivide dati personali per finalità pubblicitarie o di marketing;",
          "utilizza reti pubblicitarie di terze parti;",
          "raccoglie informazioni di pagamento.",
        ],
      },
      {
        id: "how-we-use-information",
        title: "4. Come utilizziamo le informazioni",
        paragraphs: [
          "Utilizziamo le informazioni solo per le seguenti finalità:",
        ],
        bullets: [
          "fornire le funzionalità principali dell'App;",
          "mostrare fermate nelle vicinanze e informazioni sul trasporto basate sulla mappa;",
          "inviare notifiche push, se abilitate;",
          "monitorare le prestazioni dell'App;",
          "migliorare affidabilità ed esperienza utente;",
          "proteggere l'App da usi impropri o problemi tecnici;",
          "rispettare obblighi di legge, ove richiesto.",
        ],
      },
      {
        id: "legal-basis",
        title: "5. Base giuridica del trattamento",
        paragraphs: [
          "Ove si applichi il GDPR, trattiamo i dati personali sulla base delle seguenti basi giuridiche:",
        ],
        bullets: [
          "Consenso: per accedere alla posizione del dispositivo e inviare notifiche push.",
          "Legittimo interesse: per migliorare le prestazioni dell'App, comprendere l'utilizzo generale, prevenire abusi e mantenere sicurezza e affidabilità dell'App.",
          "Obbligo legale: quando il trattamento è necessario per rispettare la legge applicabile.",
        ],
        after: [
          "Puoi revocare il consenso per l'accesso alla posizione o per le notifiche in qualsiasi momento dalle impostazioni del dispositivo.",
        ],
      },
      {
        id: "third-party-services",
        title: "6. Servizi di terze parti",
        paragraphs: [
          "Prossimo può utilizzare servizi di terze parti per gestire e migliorare l'App, inclusi:",
        ],
        bullets: [
          "Expo Insights per informazioni di base su utilizzo e prestazioni dell'app;",
          "Apple Maps per funzionalità di mappa sui dispositivi supportati;",
          "Google Maps per funzionalità di mappa sui dispositivi supportati;",
          "fornitori di infrastruttura e hosting necessari per il funzionamento dell'App.",
        ],
        after: [
          "Queste terze parti possono trattare dati secondo le rispettive informative sulla privacy.",
        ],
      },
      {
        id: "data-sharing",
        title: "7. Condivisione dei dati",
        paragraphs: [
          "Non vendiamo dati personali.",
          "Possiamo condividere informazioni limitate solo quando necessario con:",
        ],
        bullets: [
          "fornitori tecnici che ci aiutano a gestire l'App;",
          "fornitori di analisi o infrastruttura;",
          "autorità pubbliche, se richiesto dalla legge.",
        ],
        after: [
          "Non condividiamo i tuoi dati personali per marketing o pubblicità di terze parti.",
        ],
      },
      {
        id: "data-retention",
        title: "8. Conservazione dei dati",
        paragraphs: [
          "Conserviamo i dati personali solo per il tempo necessario alle finalità descritte nella presente Informativa sulla privacy.",
          "I dati sulla posizione precisa non vengono memorizzati sui nostri server.",
          "I token per le notifiche push possono essere conservati finché le notifiche sono abilitate o per il tempo necessario a fornire la funzionalità di notifica.",
          "Le informazioni tecniche e di utilizzo possono essere conservate per un periodo limitato per monitorare le prestazioni, risolvere problemi e migliorare l'App.",
        ],
      },
      {
        id: "security",
        title: "9. Sicurezza",
        paragraphs: [
          "Utilizziamo misure tecniche e organizzative ragionevoli per proteggere le informazioni trattate tramite l'App.",
          "Tuttavia, nessun metodo di trasmissione o archiviazione è completamente sicuro e non possiamo garantire una sicurezza assoluta.",
        ],
      },
      {
        id: "your-rights",
        title: "10. I tuoi diritti",
        paragraphs: [
          "Ove applicabile, anche ai sensi del GDPR, potresti avere il diritto di:",
        ],
        bullets: [
          "accedere ai tuoi dati personali;",
          "richiedere la rettifica di dati inesatti;",
          "richiedere la cancellazione dei tuoi dati;",
          "opporti a determinati trattamenti;",
          "limitare determinati trattamenti;",
          "revocare il consenso;",
          "richiedere la portabilità dei dati, ove applicabile;",
          "presentare un reclamo a un'autorità per la protezione dei dati.",
        ],
        after: [
          "In Italia puoi contattare il Garante per la protezione dei dati personali.",
          "Per esercitare i tuoi diritti, contattaci all'indirizzo:",
        ],
      },
      {
        id: "childrens-privacy",
        title: "11. Privacy dei minori",
        paragraphs: [
          "Prossimo non è destinata a minori che non abbiano l'età richiesta dalla legge applicabile per utilizzare servizi digitali senza il consenso dei genitori.",
          "Non raccogliamo consapevolmente dati personali da minori.",
        ],
      },
      {
        id: "international-transfers",
        title: "12. Trasferimenti internazionali",
        paragraphs: [
          "Alcuni fornitori di servizi utilizzati dall'App possono trattare dati al di fuori del tuo paese di residenza.",
          "Ove richiesto, ci basiamo su garanzie adeguate per i trasferimenti internazionali di dati.",
        ],
      },
      {
        id: "changes",
        title: "13. Modifiche alla presente Informativa sulla privacy",
        paragraphs: [
          "Possiamo aggiornare la presente Informativa sulla privacy di tanto in tanto.",
          "In caso di modifiche, aggiorneremo la data di entrata in vigore sopra indicata e pubblicheremo la versione aggiornata nell'App o sul nostro sito web.",
        ],
      },
      {
        id: "contact",
        title: "14. Contatti",
        paragraphs: [
          "Per domande sulla presente Informativa sulla privacy o su come vengono gestiti i tuoi dati, contatta:",
        ],
      },
    ],
  },
} satisfies Record<SupportedLanguage, PrivacyPolicyContent>;
